name: maui
description: Literacy application for children

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  animated_text_kit: ^1.3.0
  image_picker: ^0.4.10
  native_device_orientation: ^0.0.3
  cupertino_icons: ^0.1.2
  sqflite: ^0.12.2+1
  uuid: ^2.0.1
  path_provider: ^0.5.0
  tuple: ^1.0.2
  json_annotation: ^2.0.0
  audioplayers: ^0.11.0
  percent_indicator: ^1.0.10
  tinycolor: ^1.0.2
  flutter_tts: ^0.2.4
  fluttery:
    git:
      https://github.com/chimple/fluttery.git
  flutter_circular_chart: "^0.1.0"
  shared_preferences: ^0.4.3
  camera: ^0.2.1
  nima: ^1.0.1
  flutter_local_notifications: ^0.4.0
  badge:
    git:
      https://github.com/chimple/Flutter-Badge.git
  intl: ^0.15.7
  intl_translation: ^0.17.2
  flutter_svg: ^0.10.3
  permission: ^0.1.1
  image: ^2.0.4
  flutter_redurx: ^0.4.3
  built_value: ^6.3.0
  built_collection: ^4.1.0
  flare_flutter: ^1.5.0
  flare_dart: ^1.4.0
  bubble_tab_indicator: ^0.1.4
  observable_state: ^0.3.0
  equatable: ^0.2.3
  storyboard:
    git: https://github.com/chimple/storyboard
  flutter_localizations:
    sdk: flutter
  tahiti:
    path: ../tahiti
  flores:
    path: ../flores
dev_dependencies:
  test: 1.6.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  video_player: "^0.7.2"
  build_runner: ^1.1.1
  built_value_generator: ^6.3.0
  json_serializable: ^2.0.0
  flutter_markdown: ^0.2.0
  get_version: ^0.1.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/
    - assets/dice_game/
    - assets/background_image/
    - assets/background_gif/
    - assets/chat_image/
    - assets/hoodie/
    - assets/animations/
    - assets/stickers/pig/
    - assets/stickers/giraffe/
    - assets/stickers/monkey/
    - assets/stickers/doggie/
    - assets/stickers/carpie/
    - assets/stickers/emoguy/
    - assets/category/
    - assets/nima_animation/
    - assets/masking/
    - assets/action/
    - assets/map/
    - assets/game/
    - assets/accessories/
    - assets/accessories/antenna_acc/
    - assets/accessories/brac_acc/
    - assets/accessories/glasses_acc/
    - assets/accessories/hat_acc/
    - assets/accessories/head_acc/
    - assets/accessories/neck_acc/
    - assets/accessories/flag_acc/
    - assets/chat/
    - assets/character/
    - assets/stories/
    - assets/stories/images/
    - assets/audio/
    - assets/stories/story_audio/
    - assets/score/
    - assets/background_flare/
    - assets/hud/
    - assets/home_screen_icons/
    - assets/topic/
    - assets/topic/asb/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: Bungee
      fonts:
        - asset: assets/fonts/Bungee-Regular.ttf
    - family: Chela one
      fonts:
        - asset: assets/fonts/ChelaOne-Regular.ttf
    - family: Gloria Hallelujah
      fonts:
        - asset: assets/fonts/GloriaHallelujah.ttf
    - family: Great vibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
    - family: Homemade apple
      fonts:
        - asset: assets/fonts/HomemadeApple-Regular.ttf
    - family: Indie Flower
      fonts:
        - asset: assets/fonts/IndieFlower.ttf
    - family: Kirang Haerang
      fonts:
        - asset: assets/fonts/KirangHaerang-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Patrick Hand
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Rock salt
      fonts:
        - asset: assets/fonts/RockSalt-Regular.ttf
    - family: Shadows into light
      fonts:
        - asset: assets/fonts/ShadowsIntoLight.ttf
